/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Barang;

import Kategori.Kategori;
import Kategori.Kategori_kontrol;
import Kategori.kategori_GUI;
import Koneksi.Koneksi;
import java.awt.Image;
import java.awt.RenderingHints.Key;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author basisb24la
 */
public class GUIBarang extends javax.swing.JFrame {

    private String folder;
    
    /**
     * Creates new form NewJFrame
     */
    public GUIBarang() {
        initComponents();
        folder = System.getProperty("user.dir") + File.separator + "images";
            cetak(folder);
            new File(folder).mkdir();
        this.setLocationRelativeTo(null);
        tombol_delete.setEnabled(false);
        teks_kode_barang.setEnabled(false);
        tampilKategori();

        dialog_barang.setVisible(false);
        dialog_barang.setSize(1000, 400);
        dialog_barang.setTitle("DAFTAR SELURUH BARANG");
        label_alamat.setVisible(false);
    }

    public void bersihkanteks() {
        teks_kode_barang.setText("");
        teks_nama_barang.setText("");
        teks_beli_sebelum.setText("");
        teks_beli_setelah.setText("");
        teks_qty_max.setText("");
        teks_qty_min.setText("");
        teks_ritel_sebelum.setText("");
        teks_ritel_setelah.setText("");
        combo_kategori.setEnabled(true);
        combo_kategori.setSelectedIndex(0);
        combo_satuan.setSelectedIndex(0);
        tombol_simpan.setText("Simpan");
        tombol_delete.setEnabled(false);
        label_gambar.setIcon(null);
    }
    
    private String gambar(String id) {
        return folder + File.separator + id.trim() + ".jpg";
    }
    private void cetak(String str) {
        System.out.println(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_barang = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dialog_tabel_barang = new javax.swing.JTable();
        tombol_cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        teks_nama_barang = new javax.swing.JTextField();
        combo_kategori = new javax.swing.JComboBox();
        combo_satuan = new javax.swing.JComboBox();
        teks_qty_min = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        teks_qty_max = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        teks_kode_barang = new javax.swing.JTextField();
        label_gambar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label_alamat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        teks_ritel_setelah = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        teks_ritel_sebelum = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        tombol_list = new javax.swing.JButton();
        tombol_simpan = new javax.swing.JButton();
        tombol_delete = new javax.swing.JButton();
        tombol_batal = new javax.swing.JButton();
        tombol_keluar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        teks_beli_sebelum = new javax.swing.JTextField();
        teks_beli_setelah = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        dialog_barang.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        dialog_barang.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("DAFTAR SELURUH BARANG"));

        dialog_tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dialog_tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dialog_tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dialog_tabel_barang);

        tombol_cetak.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        tombol_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1442483829_Print.png"))); // NOI18N
        tombol_cetak.setText("CETAK");
        tombol_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(tombol_cetak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(tombol_cetak))
        );

        javax.swing.GroupLayout dialog_barangLayout = new javax.swing.GroupLayout(dialog_barang.getContentPane());
        dialog_barang.getContentPane().setLayout(dialog_barangLayout);
        dialog_barangLayout.setHorizontalGroup(
            dialog_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialog_barangLayout.setVerticalGroup(
            dialog_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/49.png"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel15.setText("DATA BARANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 51, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Nama barang");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Kategori");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Status");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Qty Min");

        combo_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_kategoriActionPerformed(evt);
            }
        });

        combo_satuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dus", "Lusin", " " }));

        teks_qty_min.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_qty_minKeyTyped(evt);
            }
        });

        jLabel6.setText("Qty Max");

        teks_qty_max.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_qty_maxKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Kode Barang");

        teks_kode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks_kode_barangActionPerformed(evt);
            }
        });

        label_gambar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label_alamat.setText("Alamat gambar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(teks_nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addComponent(combo_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(teks_qty_min, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(teks_qty_max, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teks_kode_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_alamat)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(label_gambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(teks_nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(teks_kode_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(combo_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(combo_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(teks_qty_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(teks_qty_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_alamat)
                .addGap(5, 5, 5))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Penjualan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 51, 0))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Ritel Setelah PPN");

        teks_ritel_setelah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teks_ritel_setelahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_ritel_setelahKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText("Ritel Sebelum PPN");

        teks_ritel_sebelum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks_ritel_sebelumActionPerformed(evt);
            }
        });
        teks_ritel_sebelum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teks_ritel_sebelumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_ritel_sebelumKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(teks_ritel_setelah, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teks_ritel_sebelum, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(teks_ritel_sebelum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(teks_ritel_setelah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tombol_list.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        tombol_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1442484052_document.png"))); // NOI18N
        tombol_list.setText("LIST");
        tombol_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_listActionPerformed(evt);
            }
        });

        tombol_simpan.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        tombol_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1442483718_Save.png"))); // NOI18N
        tombol_simpan.setText("SIMPAN");
        tombol_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_simpanActionPerformed(evt);
            }
        });

        tombol_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1442483766_Delete.png"))); // NOI18N
        tombol_delete.setText("HAPUS");
        tombol_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_deleteActionPerformed(evt);
            }
        });

        tombol_batal.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        tombol_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1442483809_Undo.png"))); // NOI18N
        tombol_batal.setText("BATAL");
        tombol_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_batalActionPerformed(evt);
            }
        });

        tombol_keluar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        tombol_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1442484041_exit.png"))); // NOI18N
        tombol_keluar.setText("KELUAR");
        tombol_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombol_list, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombol_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombol_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombol_batal, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombol_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addGap(117, 117, 117))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tombol_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombol_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Pembelian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 51, 0))); // NOI18N

        teks_beli_sebelum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teks_beli_sebelumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_beli_sebelumKeyTyped(evt);
            }
        });

        teks_beli_setelah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teks_beli_setelahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teks_beli_setelahKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setText("Ritel Sebelum PPN");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setText("Ritel Setelah PPN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(teks_beli_setelah, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teks_beli_sebelum, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(teks_beli_setelah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(teks_beli_sebelum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombol_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_cetakActionPerformed
        try {
            // TODO add your handling code here:
            dialog_barang.dispose();
            String namafile = "./Laporan/report1.jasper";
            Map<String, Object> params = new HashMap<String, Object>();
//            params.put("tgl1", tanggal1);
//            params.put("tgl2", tanggal2);
            JasperPrint jasperPrint = JasperFillManager.fillReport(namafile, params, new Koneksi().getDBConnection());
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(GUIBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombol_cetakActionPerformed

    private void combo_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_kategoriActionPerformed
        // TODO add your handling code here:
        String combo = combo_kategori.getSelectedItem().toString();
        String split[] = combo.split(" ");
        String kodekategori = split[0];
        String bantu;
        int kode;
        try {
            kode = Barang_Kontrol.getkoneksibarang().kodeOtomatisCekBarang(kodekategori) + 1;
            if (kode == 1) {
                bantu = "001";
                teks_kode_barang.setText(kodekategori + bantu);
            } else if (kode < 10) {
                bantu = "00";
                teks_kode_barang.setText(kodekategori + bantu + Integer.toString(kode));
            } else if (10 <= kode && kode < 100) {
                bantu = "0";
                teks_kode_barang.setText(kodekategori + bantu + Integer.toString(kode));
            } else {
                teks_kode_barang.setText(kodekategori + Integer.toString(kode));
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUIBarang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_combo_kategoriActionPerformed

    private void tombol_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_batalActionPerformed
        // TODO add your handling code here:
        bersihkanteks();
    }//GEN-LAST:event_tombol_batalActionPerformed

    private void tombol_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_keluarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
////        this.dispose();
//        System.exit(WIDTH);
    }//GEN-LAST:event_tombol_keluarActionPerformed

    private void teks_kode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks_kode_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teks_kode_barangActionPerformed

    private void tombol_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_simpanActionPerformed
        // TODO add your handling code here:
        if (teks_nama_barang.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Silahkan isi nama barang");
        } else {
            Barang brg = new Barang();
            brg.setImage(teks_kode_barang.getText());
            brg.setKodebarang(teks_kode_barang.getText());
            brg.setNamabarang(teks_nama_barang.getText());
            String[] split = combo_kategori.getSelectedItem().toString().split(" ");
            Kategori kat = new Kategori();
            kat.setKode(split[0]);
            brg.setKategori(kat);
            brg.setSatuan(combo_satuan.getSelectedItem().toString());
            brg.setImage(label_alamat.getText());

            if (teks_qty_min.getText().equals("")) {
                brg.setQtymin(0);
            } else {
                brg.setQtymin(new Integer(teks_qty_min.getText()));
            }
            if (teks_qty_max.getText().equals("")) {
                brg.setQtymax(0);
            } else {
                brg.setQtymax(new Integer(teks_qty_max.getText()));
            }
            if (teks_beli_sebelum.getText().equals("")) {
                brg.setBeliSebelum(0);
            } else {
                brg.setBeliSebelum(new Double(teks_beli_sebelum.getText()));
            }
            if (teks_beli_setelah.getText().equals("")) {
                brg.setBeliSesudah(0);
            } else {
                brg.setBeliSesudah(new Double(teks_beli_setelah.getText()));
            }
            if (teks_ritel_sebelum.getText().equals("")) {
                brg.setRitelSebelum(0);
            } else {
                brg.setRitelSebelum(new Double(teks_ritel_sebelum.getText()));
            }
            if (teks_ritel_setelah.getText().equals("")) {
                brg.setRitelSesudah(0);
            } else {
                brg.setRitelSesudah(new Double(teks_ritel_setelah.getText()));
            }
            if (!label_alamat.getText().equals("")) {
                    try {
                        new NIOCopier(label_alamat.getText(), gambar(teks_kode_barang.getText()));
                    } catch (IOException ex) {
                        Logger.getLogger(GUIBarang.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            brg.setImage(teks_kode_barang.getText());

            if (brg.getQtymax() >= brg.getQtymin()) {
                try {
                    Barang_Kontrol bk = Barang_Kontrol.getkoneksibarang();

                    if (tombol_simpan.getText().equals("Update")) {
                        bk.updateBarang(brg);
                        JOptionPane.showMessageDialog(null, "Data terupdate");
                    } else {
                        bk.tambahBarang(brg);
                        JOptionPane.showMessageDialog(null, "Data tersimpan");
                    }

                    bersihkanteks();
                } catch (SQLException ex) {
                    Logger.getLogger(GUIBarang.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Stok maksimal tidak boleh lurang dari stok minimal");
            }
        }

    }

    private void tombol_hapusActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }//GEN-LAST:event_tombol_simpanActionPerformed

    private void teks_qty_minKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_qty_minKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter)) || karakter == KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_qty_minKeyTyped

    private void teks_qty_maxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_qty_maxKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter)) || karakter == KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_qty_maxKeyTyped

    private void teks_ritel_setelahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_ritel_setelahKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter)) || karakter == KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_ritel_setelahKeyTyped

    private void teks_ritel_sebelumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks_ritel_sebelumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teks_ritel_sebelumActionPerformed

    private void teks_ritel_sebelumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_ritel_sebelumKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter)) || karakter == KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_ritel_sebelumKeyTyped

    private void teks_beli_setelahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_beli_setelahKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter)) || karakter == KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_beli_setelahKeyTyped

    private void teks_beli_sebelumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_beli_sebelumKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter)) || karakter == KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_teks_beli_sebelumKeyTyped

    private void teks_ritel_setelahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_ritel_setelahKeyReleased
        // TODO add your handling code here:
        if (!teks_ritel_setelah.getText().equals("")) {
            long ritelsetelah = new Long(teks_ritel_setelah.getText()) - (new Long(teks_ritel_setelah.getText()) * 10 / 100);
            teks_ritel_sebelum.setText(String.valueOf(ritelsetelah));
        } else {
            teks_ritel_sebelum.setText("");
        }
    }//GEN-LAST:event_teks_ritel_setelahKeyReleased

    private void teks_ritel_sebelumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_ritel_sebelumKeyReleased
        // TODO add your handling code here:
        if (!teks_ritel_sebelum.getText().equals("")) {
            long ritelsetelah = new Long(teks_ritel_sebelum.getText()) + (new Long(teks_ritel_sebelum.getText()) * 10 / 100);
            teks_ritel_setelah.setText(String.valueOf(ritelsetelah));
        } else {
            teks_ritel_setelah.setText("");
        }
    }//GEN-LAST:event_teks_ritel_sebelumKeyReleased

    private void teks_beli_setelahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_beli_setelahKeyReleased
        // TODO add your handling code here:
        if (!teks_beli_setelah.getText().equals("")) {
            long ritelsetelah = new Long(teks_beli_setelah.getText()) - (new Long(teks_beli_setelah.getText()) * 10 / 100);
            teks_beli_sebelum.setText(String.valueOf(ritelsetelah));
        } else {
            teks_beli_sebelum.setText("");
        }
    }//GEN-LAST:event_teks_beli_setelahKeyReleased

    private void teks_beli_sebelumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teks_beli_sebelumKeyReleased
        // TODO add your handling code here:
        if (!teks_beli_sebelum.getText().equals("")) {
            long ritelsetelah = new Long(teks_beli_sebelum.getText()) + (new Long(teks_beli_sebelum.getText()) * 10 / 100);
            teks_beli_setelah.setText(String.valueOf(ritelsetelah));
        } else {
            teks_beli_setelah.setText("");
        }
    }//GEN-LAST:event_teks_beli_sebelumKeyReleased

    private void tombol_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_listActionPerformed
        // TODO add your handling code here:
        tampilisibarang();
        dialog_barang.setLocationRelativeTo(null);
        dialog_barang.setVisible(true);
    }//GEN-LAST:event_tombol_listActionPerformed

    private void dialog_tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dialog_tabel_barangMouseClicked

        // TODO add your handling code here:
        int row = dialog_tabel_barang.getSelectedRow();
        String kdbrg = dialog_tabel_barang.getValueAt(row, 1).toString();
        String nmbrg = dialog_tabel_barang.getValueAt(row, 2).toString();
        String kdktgr = dialog_tabel_barang.getValueAt(row, 3).toString();
        String satuan = dialog_tabel_barang.getValueAt(row, 4).toString();
        String min = dialog_tabel_barang.getValueAt(row, 5).toString();
        String max = dialog_tabel_barang.getValueAt(row, 6).toString();
        String rtlstl = dialog_tabel_barang.getValueAt(row, 7).toString();
        String rtsbl = dialog_tabel_barang.getValueAt(row, 8).toString();
        String blstl = dialog_tabel_barang.getValueAt(row, 9).toString();
        String blsbl = dialog_tabel_barang.getValueAt(row, 10).toString();

        teks_nama_barang.setText(nmbrg);
        teks_qty_max.setText(max);
        teks_qty_min.setText(min);
        combo_satuan.setSelectedItem(satuan);
        teks_ritel_setelah.setText(rtlstl);
        teks_ritel_sebelum.setText(rtsbl);
        teks_beli_setelah.setText(blstl);
        teks_beli_sebelum.setText(blsbl);
        Toolkit tool = Toolkit.getDefaultToolkit();
            Image ig = tool.getImage(gambar(kdbrg));
            Image imagerez = ig.getScaledInstance(100, 100, Image.SCALE_DEFAULT);
            ImageIcon igm = new ImageIcon(imagerez);
            label_gambar.setIcon(igm);
        try {
            Kategori k = Kategori_kontrol.getkoneksikategori().CariKategori(kdktgr);
            combo_kategori.setSelectedItem(kdktgr + " " + k.getNama());
            combo_kategori.setEnabled(false);
            teks_kode_barang.setText(kdbrg);
            tombol_delete.setEnabled(true);
            tombol_simpan.setText("Update");
            dialog_barang.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(GUIBarang.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_dialog_tabel_barangMouseClicked

    private void tombol_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_deleteActionPerformed
        // TODO add your handling code here:
        if (teks_kode_barang.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Tidak ada data yang dihapus");
        } else {
            try {
                Barang_Kontrol br = Barang_Kontrol.getkoneksibarang();
                br.HapusBarang(teks_kode_barang.getText());
                JOptionPane.showMessageDialog(rootPane, "Data sudah terhapus");
                tampilKategori();
                bersihkanteks();
            } catch (SQLException ex) {
                Logger.getLogger(GUIBarang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tombol_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // jButton1 merupakan button untuk "Browse" gambar yang ingin dimasukkan
        javax.swing.JFileChooser jfc = new JFileChooser();
        FileFilter jpgFilter, gifFilter, bothFilter;
        jpgFilter = new FileNameExtensionFilter("Gambar JPEG", "jpg");
        gifFilter = new FileNameExtensionFilter("Gambar GIF", "gif");
        bothFilter = new FileNameExtensionFilter("Gambar JPEG dan GIF", "jpg", "gif");
        jfc.setAcceptAllFileFilterUsed(false);
        jfc.addChoosableFileFilter(jpgFilter);
        jfc.addChoosableFileFilter(gifFilter);
        jfc.addChoosableFileFilter(bothFilter);
        if (jfc.showOpenDialog(this) == jfc.APPROVE_OPTION) {
            String f = jfc.getSelectedFile().toString();
            label_alamat.setText(f);
            // label alamat berguna untuk menampilkan path dari gambar yang akan dimasukkan
            
            Toolkit tool = Toolkit.getDefaultToolkit();
            Image ig = tool.getImage(f);
            Image imagerez = ig.getScaledInstance(100, 100, Image.SCALE_DEFAULT);
            ImageIcon igm = new ImageIcon(imagerez);
            label_gambar.setIcon(igm);
            label_alamat.setVisible(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void tampilisibarang() {
        try {
            List<Barang> br = Barang_Kontrol.getkoneksibarang().LihatSemuaBarang();
            BarangTabelModel model = new BarangTabelModel(br);
            dialog_tabel_barang.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(GUIBarang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void tampilKategori() {
        try {
            List<Kategori> kat = Kategori_kontrol.getkoneksikategori().LihatSemuaKategori();
            for (int i = 0; i < kat.size(); i++) {
                combo_kategori.addItem(kat.get(i).getKode() + " " + kat.get(i).getNama());
            }

        } catch (SQLException ex) {
            Logger.getLogger(GUIBarang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUIBarang().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_kategori;
    private javax.swing.JComboBox combo_satuan;
    private javax.swing.JDialog dialog_barang;
    private javax.swing.JTable dialog_tabel_barang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel label_alamat;
    private javax.swing.JLabel label_gambar;
    private javax.swing.JTextField teks_beli_sebelum;
    private javax.swing.JTextField teks_beli_setelah;
    private javax.swing.JTextField teks_kode_barang;
    private javax.swing.JTextField teks_nama_barang;
    private javax.swing.JTextField teks_qty_max;
    private javax.swing.JTextField teks_qty_min;
    private javax.swing.JTextField teks_ritel_sebelum;
    private javax.swing.JTextField teks_ritel_setelah;
    private javax.swing.JButton tombol_batal;
    private javax.swing.JButton tombol_cetak;
    private javax.swing.JButton tombol_delete;
    private javax.swing.JButton tombol_keluar;
    private javax.swing.JButton tombol_list;
    private javax.swing.JButton tombol_simpan;
    // End of variables declaration//GEN-END:variables

     public class NIOCopier {

        public NIOCopier(String asal, String tujuan) throws IOException {
            FileInputStream inFile = new FileInputStream(asal);
            FileOutputStream outFile = new FileOutputStream(tujuan);
            FileChannel inChannel = inFile.getChannel();
            FileChannel outChannel = outFile.getChannel();
            for (ByteBuffer buffer = ByteBuffer.allocate(1024 * 1024);
                    inChannel.read(buffer) != -1;
                    buffer.clear()) {
                buffer.flip();
                while (buffer.hasRemaining()) {
                    outChannel.write(buffer);
                }
            }
            inChannel.close();
            outChannel.close();
        }
    }
}
