/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Kategori;

import Barang.Barang;
import Barang.GUIBarang;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author basisb06
 */
public class kategori_GUI extends javax.swing.JDialog {

    /**
     * Creates new form kategori_GUI
     */
    public kategori_GUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        tombol_hapus.setEnabled(false);
        tampilKategori();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        teks_kode = new javax.swing.JTextField();
        teks_nama = new javax.swing.JTextField();
        tombol_simpan = new javax.swing.JButton();
        tombol_hapus = new javax.swing.JButton();
        tombol_batal = new javax.swing.JButton();
        tombol_tutup = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kategori = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/34.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setText("KATEGORI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setText("KODE KATEGORI");

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setText("NAMA KATEGORI");

        teks_kode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        teks_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks_kodeActionPerformed(evt);
            }
        });
        teks_kode.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                teks_kodePropertyChange(evt);
            }
        });

        teks_nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tombol_simpan.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        tombol_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1442483718_Save.png"))); // NOI18N
        tombol_simpan.setText("TAMBAH");
        tombol_simpan.setToolTipText("Tambahkan data yang telah dimasukkan");
        tombol_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_simpanActionPerformed(evt);
            }
        });

        tombol_hapus.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        tombol_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1442483766_Delete.png"))); // NOI18N
        tombol_hapus.setText("HAPUS");
        tombol_hapus.setToolTipText("Hapus data yang telah dipilih");
        tombol_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_hapusActionPerformed(evt);
            }
        });

        tombol_batal.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        tombol_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1442483766_Delete.png"))); // NOI18N
        tombol_batal.setText("BATAL");
        tombol_batal.setToolTipText("Batalkan transaksi");
        tombol_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_batalActionPerformed(evt);
            }
        });

        tombol_tutup.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        tombol_tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1442484041_exit.png"))); // NOI18N
        tombol_tutup.setText("TUTUP");
        tombol_tutup.setToolTipText("Tutup aplikasi");
        tombol_tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_tutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tombol_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol_batal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol_tutup))
                    .addComponent(teks_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teks_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(teks_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(teks_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol_simpan)
                    .addComponent(tombol_hapus)
                    .addComponent(tombol_batal)
                    .addComponent(tombol_tutup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabel_kategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Kode Kategori", "Nama Kategori"
            }
        ));
        tabel_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_kategori);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void bersihkanteks(){
        teks_kode.setText("");
        teks_nama.setText("");
        tombol_simpan.setText("Simpan");
        teks_kode.setEditable(true);
        tombol_hapus.setEnabled(false);
    }
    
    public void tampilKategori(){
        try {
            List<Kategori> kat = Kategori_kontrol.getkoneksikategori().LihatSemuaKategori();
            KategoriTabelModel model = new KategoriTabelModel(kat);
            tabel_kategori.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(kategori_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void tombol_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_simpanActionPerformed
        // TODO add your handling code here:
        if (teks_kode.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Silahkan isi kode kategori");
        }else if(teks_nama.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Silahkan masukkan nama kategori");
        }else{
            try {
                
                String kode= teks_kode.getText();
                String nama=teks_nama.getText();
              
                Kategori kat= new Kategori(kode, nama);
                Kategori_kontrol k= Kategori_kontrol.getkoneksikategori();
                if (tombol_simpan.getText().equals("UPDATE")) {
                    k.updateKategori(kat);
                    JOptionPane.showMessageDialog(rootPane, "Data sudah terbaharui");
                }else{
//                    Kategori ktgr= Kategori_kontrol.getkoneksikategori().CariKategori(kode);
                    boolean status = Kategori_kontrol.getkoneksikategori().CariKode(kode);
                    if (status==true) {
                        JOptionPane.showMessageDialog(rootPane, "Kode "+kode+" Sudah digunakan\nSilahkan gunakan kode yang lain.");
                        teks_kode.setText("");
                    }
                    else{
                        k.tambahKategori(kat);
                        JOptionPane.showMessageDialog(rootPane, "Data Sudah tersimpan");
                    }
                }
                bersihkanteks();
                tampilKategori();
            } catch (SQLException ex) {
                Logger.getLogger(kategori_GUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Gagal menyimpan"+ex.getMessage());
            }
        }
    }//GEN-LAST:event_tombol_simpanActionPerformed

    private void tombol_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_hapusActionPerformed
        // TODO add your handling code here:
        if (teks_kode.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Tidak ada data yang dihapus");
        }else{
            try {
                Kategori_kontrol k= Kategori_kontrol.getkoneksikategori();
                k.HapusKategori(teks_kode.getText());
                JOptionPane.showMessageDialog(rootPane, "Data sudah terhapus");
                tampilKategori();
                bersihkanteks();
            } catch (SQLException ex) {
                Logger.getLogger(kategori_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tombol_hapusActionPerformed

    private void teks_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks_kodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_teks_kodeActionPerformed

    private void tabel_kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kategoriMouseClicked
        try {
            // TODO add your handling code here:
            int row = tabel_kategori.getSelectedRow();
            String kode= tabel_kategori.getValueAt(row, 1).toString();
            Kategori ktgr= Kategori_kontrol.getkoneksikategori().CariKategori(kode);
            String nama= tabel_kategori.getValueAt(row, 2).toString();
            teks_kode.setText(kode);
            teks_nama.setText(ktgr.getNama());
            tombol_simpan.setText("UPDATE");
            teks_kode.setEditable(false);
            tombol_hapus.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(kategori_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabel_kategoriMouseClicked

    private void tombol_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_batalActionPerformed
        // TODO add your handling code here:
        
        bersihkanteks();
    }//GEN-LAST:event_tombol_batalActionPerformed

    private void tombol_tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_tutupActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_tombol_tutupActionPerformed

    private void teks_kodePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_teks_kodePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_teks_kodePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kategori_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kategori_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kategori_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kategori_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                kategori_GUI dialog = new kategori_GUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_kategori;
    private javax.swing.JTextField teks_kode;
    private javax.swing.JTextField teks_nama;
    private javax.swing.JButton tombol_batal;
    private javax.swing.JButton tombol_hapus;
    private javax.swing.JButton tombol_simpan;
    private javax.swing.JButton tombol_tutup;
    // End of variables declaration//GEN-END:variables
}
